// All error messages were generated by AI, idk im not creative enough to think of a quirky one
// javadocs created by AI

package baron.command;

import baron.data.BaronState;
import baron.exception.BaronException;
import baron.exception.FormatException;
import baron.task.Deadline;
import baron.task.Event;
import baron.task.Task;
import baron.task.Todo;

/**
 * Represents the valid user commands supported by the Baron application.
 * Each enum constant defines how the command is executed against the current task list.
 */
public enum Commands {
    BYE {
        @Override
        public String execute(String args) {
            BaronState.exit();
            return "";
        }

    },
    LIST {
        @Override
        public String execute(String args) {
            StringBuilder sb = new StringBuilder();
            sb.append("Here are the tasks in your list:\n");
            int i = 1;
            for (Task t : BaronState.getTasks()) {
                sb.append(i).append(".").append(t).append("\n");
                i++;
            }
            return sb.toString();
        }
    },
    MARK {
        @Override
        public String execute(String args) throws BaronException {
            int index = parseTaskIndex(args, "mark");
            BaronState.markTaskAsDone(index);
            return formatTaskAction("Nice! I've marked this task as done:", BaronState.getTasks().get(index));
        }
    },
    UNMARK {
        @Override
        public String execute(String args) throws BaronException {
            int index = parseTaskIndex(args, "unmark");
            BaronState.unmarkTask(index);
            return formatTaskAction("OK, I've marked this task as not done yet:", BaronState.getTasks().get(index));
        }
    },
    TODO {
        @Override
        public String execute(String args) throws BaronException {
            if (args.isEmpty()) {
                throw new FormatException("todo", "todo <description>");
            }
            Task t = new Todo(args);
            BaronState.addTask(t);
            return formatAddedTask(t);
        }
    },
    DEADLINE {
        @Override
        public String execute(String args) throws BaronException {
            String[] parts = args.split(" /by ");
            if (parts.length < 2) {
                throw new FormatException("deadline", "deadline <description> /by <date>");
            }
            Task t = new Deadline(parts[0], parts[1]);
            BaronState.addTask(t);
            return formatAddedTask(t);
        }
    },
    EVENT {
        @Override
        public String execute(String args) throws BaronException {
            String[] parts = args.split(" /from | /to ");
            if (parts.length < 3) {
                throw new FormatException("event", "event <description> /from <start time> /to <end time>");
            }
            Task t = new Event(parts[0], parts[1], parts[2]);
            BaronState.addTask(t);
            return formatAddedTask(t);
        }
    },
    DELETE {
        @Override
        public String execute(String args) throws BaronException {
            int index = parseTaskIndex(args, "delete");
            Task t = BaronState.delete(index);
            String response = formatTaskAction("Noted. I've removed this task:", t);
            response += "\nNow you have " + BaronState.getTasks().size() + " tasks in the list.";
            return response;
        }
    },
    FIND {
        @Override
        public String execute(String args) throws BaronException {
            if (args.isEmpty()) {
                throw new FormatException("find", "find <keyword>");
            }
            boolean found = false;
            int i = 1;
            StringBuilder sb = new StringBuilder();
            for (Task t : BaronState.getTasks()) {
                if (t.getName().contains(args)) {
                    if (!found) {
                        sb.append("Here are the matching tasks in your list:");
                        found = true;
                    }
                    sb.append("\n").append(i).append(".").append(t);
                    i++;
                }
            }
            if (!found) {
                sb.append("There are no matching tasks in your list:");
            }
            return sb.toString();
        }
    };

    // AI suggested use of abstract method to execute commands
    /**
     * Executes the action associated with this command.
     *
     * @param args the raw arguments supplied with the command.
     * @throws BaronException if the command arguments are invalid.
     */
    public abstract String execute(String args) throws BaronException;

    /** Formats the common confirmation shown after adding a task. */
    private static String formatAddedTask(Task task) {
        StringBuilder sb = new StringBuilder();
        sb.append("Got it. I've added this task:");
        sb.append("\n  ").append(task);
        sb.append("\nNow you have ").append(BaronState.getTasks().size()).append(" tasks in the list.");
        return sb.toString();
    }

    /** Formats the common response shown after acting on an existing task. */
    private static String formatTaskAction(String message, Task task) {
        return message + "\n  " + task;
    }

    /** Converts a one-based task number into the zero-based index used by the state. */
    private static int parseTaskIndex(String args, String commandName) throws BaronException {
        try {
            return Integer.parseInt(args) - 1;
        } catch (NumberFormatException e) {
            throw new FormatException(commandName, commandName + " <task number>");
        }
    }

    /**
     * Parses a raw command string into the matching enum constant.
     *
     * @param input the command input from the user.
     * @return the corresponding {@link Commands} entry.
     * @throws BaronException if the input does not match a supported command.
     */
    public static Commands parse(String input) throws BaronException {
        // AI suggested use of valueOf to parse the input string to enum constant
        try {
            return Commands.valueOf(input.toUpperCase());
        } catch (IllegalArgumentException e) {
            throw new BaronException("Invalid command. Please try again.");
        }
    }
}
