// All error messages were generated by AI, idk im not creative enough to think of a quirky one
// javadocs created by AI

package baron.command;

import baron.data.BaronState;
import baron.exception.BaronException;
import baron.exception.FormatException;
import baron.task.*;

/**
 * Represents the valid user commands supported by the Baron application.
 * Each enum constant defines how the command is executed against the current task list.
 */
public enum Commands {
    BYE {
        @Override
        public void execute(String args) {
            BaronState.exit();
        }

    },
    LIST {
        @Override
        public void execute(String args) {
            System.out.println("Here are the tasks in your list:");
            int i = 1;
            for (Task t : BaronState.getTasks()) {
                System.out.println(i + "." + t);
                i++;
            }
        }
    },
    MARK {
        @Override
        public void execute(String args) throws BaronException {
            try {
                int index = Integer.parseInt(args) - 1;
                BaronState.markTaskAsDone(index);
                System.out.println("Nice! I've marked this task as done:");
                System.out.println("  " + BaronState.getTasks().get(index));
            } catch (NumberFormatException e) {
                throw new FormatException("mark", "mark <task number>");
            }
        }
    },
    UNMARK {
        @Override
        public void execute(String args) throws BaronException {
            try {
                int index = Integer.parseInt(args) - 1;
                BaronState.unmarkTask(index);
                System.out.println("OK, I've marked this task as not done yet:");
                System.out.println("  " + BaronState.getTasks().get(index));
            } catch (NumberFormatException e) {
                throw new FormatException("unmark", "unmark <task number>");
            }
        }
    },
    TODO {
        @Override
        public void execute(String args) throws BaronException {
            if (args.isEmpty()) {
                throw new FormatException("todo", "todo <description>");
            }
            Task t = new Todo(args);
            BaronState.addTask(t);
            System.out.println("Got it. I've added this task:");
            System.out.println("  " + t);
            System.out.println("Now you have " + BaronState.getTasks().size() + " tasks in the list.");
        }
    },
    DEADLINE {
        @Override
        public void execute(String args) throws BaronException {
            String[] parts = args.split(" /by ");
            if (parts.length < 2) {
                throw new FormatException("deadline", "deadline <description> /by <date>");
            }
            Task t = new Deadline(parts[0], parts[1]);
            BaronState.addTask(t);
            System.out.println("Got it. I've added this task:");
            System.out.println("  " + t);
            System.out.println("Now you have " + BaronState.getTasks().size() + " tasks in the list.");
        }
    },
    EVENT {
        @Override
        public void execute(String args) throws BaronException {
            String[] parts = args.split(" /from | /to ");
            if (parts.length < 3) {
                throw new FormatException("event", "event <description> /from <start time> /to <end time>");
            }
            Task t = new Event(parts[0], parts[1], parts[2]);
            BaronState.addTask(t);
            System.out.println("Got it. I've added this task:");
            System.out.println("  " + t);
            System.out.println("Now you have " + BaronState.getTasks().size() + " tasks in the list.");
        }
    },
    DELETE {
        @Override
        public void execute(String args) throws BaronException {
            try {
                int index = Integer.parseInt(args) - 1;
                Task t = BaronState.delete(index);
                System.out.println("Noted. I've removed this task:");
                System.out.println("  " + t);
                System.out.println("Now you have " + BaronState.getTasks().size() + " tasks in the list.");
            } catch (NumberFormatException e) {
                throw new FormatException("delete", "delete <task number>");
            }
        }
    },
    FIND {
        @Override
        public void execute(String args) throws BaronException {
            if (args.isEmpty()) {
                throw new FormatException("find", "find <keyword>");
            }
            boolean found = false;
            int i = 1;
            for (Task t : BaronState.getTasks()) {
                if (t.getName().contains(args)) {
                    if (!found) {
                        System.out.println("Here are the matching tasks in your list:");
                        found = true;
                    }
                    System.out.println(i + "." + t);
                    i++;
                }
            }
            if (!found) {
                System.out.println("There are no matching tasks in your list:");
            }
        }
    };

    // AI suggested use of abstract method to execute commands
    /**
     * Executes the action associated with this command.
     *
     * @param args the raw arguments supplied with the command.
     * @throws BaronException if the command arguments are invalid.
     */
    public abstract void execute(String args) throws BaronException;

    /**
     * Parses a raw command string into the matching enum constant.
     *
     * @param input the command input from the user.
     * @return the corresponding {@link Commands} entry.
     * @throws BaronException if the input does not match a supported command.
     */
    public static Commands parse(String input) throws BaronException {
        // AI suggested use of valueOf to parse the input string to enum constant
        try {
            return Commands.valueOf(input.toUpperCase());
        } catch (IllegalArgumentException e) {
            throw new BaronException("Invalid command. Please try again.");
        }
    }
}
