// All error messages were generated by AI, idk im not creative enough to think of a quirky one

import task.*;

import exceptions.BaronException;
import exceptions.FormatException;

public enum Commands {
    BYE {
        @Override
        public void execute(String args) {
            BaronState.exit();
        }

    },
    LIST {
        @Override
        public void execute(String args) {
            System.out.println("Here are the tasks in your list:");
            int i = 1;
            for (Task t : BaronState.getTasks()) {
                System.out.println(i + "." + t);
                i++;
            }
        }
    },
    MARK {
        @Override
        public void execute(String args) throws BaronException {
            try {
                int index = Integer.parseInt(args) - 1;
                BaronState.markTaskAsDone(index);
                System.out.println("Nice! I've marked this task as done:");
                System.out.println("  " + BaronState.getTasks().get(index));
            } catch (NumberFormatException e) {
                throw new FormatException("mark", "mark <task number>");
            }
        }
    },
    UNMARK {
        @Override
        public void execute(String args) throws BaronException {
            try {
                int index = Integer.parseInt(args) - 1;
                BaronState.unmarkTask(index);
                System.out.println("OK, I've marked this task as not done yet:");
                System.out.println("  " + BaronState.getTasks().get(index));
            } catch (NumberFormatException e) {
                throw new FormatException("unmark", "unmark <task number>");
            }
        }
    },
    TODO {
        @Override
        public void execute(String args) throws BaronException {
            if (args.isEmpty()) {
                throw new FormatException("todo", "todo <description>");
            }
            Task t = new Todo(args);
            BaronState.getTasks().add(t);
            System.out.println("Got it. I've added this task:");
            System.out.println("  " + t);
            System.out.println("Now you have " + BaronState.getTasks().size() + " tasks in the list.");
        }
    },
    DEADLINE {
        @Override
        public void execute(String args) throws BaronException {
            String[] parts = args.split(" /by ");
            if (parts.length < 2) {
                throw new FormatException("deadline", "deadline <description> /by <date>");
            }
            Task t = new Deadline(parts[0], parts[1]);
            BaronState.getTasks().add(t);
            System.out.println("Got it. I've added this task:");
            System.out.println("  " + t);
            System.out.println("Now you have " + BaronState.getTasks().size() + " tasks in the list.");
        }
    },
    EVENT {
        @Override
        public void execute(String args) throws BaronException {
            String[] parts = args.split(" /from | /to ");
            if (parts.length < 3) {
                throw new FormatException("event", "event <description> /from <start time> /to <end time>");
            }
            Task t = new Event(parts[0], parts[1], parts[2]);
            BaronState.getTasks().add(t);
            System.out.println("Got it. I've added this task:");
            System.out.println("  " + t);
            System.out.println("Now you have " + BaronState.getTasks().size() + " tasks in the list.");
        }
    },
    DELETE {
        @Override
        public void execute(String args) throws BaronException {
            try {
                int index = Integer.parseInt(args) - 1;
                Task t = BaronState.delete(index);
                System.out.println("Noted. I've removed this task:");
                System.out.println("  " + t);
                System.out.println("Now you have " + BaronState.getTasks().size() + " tasks in the list.");
            } catch (NumberFormatException e) {
                throw new FormatException("delete", "delete <task number>");
            }
        }
    };


    // AI suggested use of abstract method to execute commands
    public abstract void execute(String args) throws BaronException;

    public static Commands parse(String input) throws BaronException {
        // AI suggested use of valueOf to parse the input string to enum constant
        try {
            return Commands.valueOf(input.toUpperCase());
        } catch (IllegalArgumentException e) {
            throw new BaronException("Invalid command. Please try again.");
        }
    }
}
