// All error messages were generated by AI, idk im not creative enough to think of a quirky one
public enum Commands {
    BYE("bye") {
        @Override
        public void execute(String args) {
            BaronState.exit();
        }

    },
    LIST("list") {
        @Override
        public void execute(String args) {
            System.out.println("Here are the tasks in your list:");
            int i = 1;
            for (Task t : BaronState.getTasks()) {
                System.out.println(i + "." + t);
                i++;
            }
        }
    },
    MARK("mark") {
        @Override
        public void execute(String args) throws BaronException {
            try {
                int index = Integer.parseInt(args) - 1;
                BaronState.markTaskAsDone(index);
                System.out.println("Nice! I've marked this task as done:");
                System.out.println("  " + BaronState.getTasks().get(index));
            } catch (NumberFormatException e) {
                throw new BaronException("Invalid input. Please provide a valid task number.");
            }
        }
    },
    UNMARK("unmark") {
        @Override
        public void execute(String args) throws BaronException {
            try {
                int index = Integer.parseInt(args) - 1;
                BaronState.unmarkTask(index);
                System.out.println("OK, I've marked this task as not done yet:");
                System.out.println("  " + BaronState.getTasks().get(index));
            } catch (NumberFormatException e) {
                throw new BaronException("Invalid input. Please provide a valid task number.");
            }
        }
    },
    TODO("todo") {
        @Override
        public void execute(String args) throws BaronException {
            if (args.isEmpty()) {
                throw new BaronException("The description of a todo cannot be empty.");
            }
            Task t = new Todo(args);
            BaronState.getTasks().add(t);
            System.out.println("Got it. I've added this task:");
            System.out.println("  " + t);
            System.out.println("Now you have " + BaronState.getTasks().size() + " tasks in the list.");
        }
    },
    DEADLINE("deadline") {
        @Override
        public void execute(String args) throws BaronException {
            String[] parts = args.split(" /by ");
            if (parts.length < 2) {
                throw new BaronException("Invalid format. Please use: deadline <description> /by <date>");
            }
            Task t = new Deadline(parts[0], parts[1]);
            BaronState.getTasks().add(t);
            System.out.println("Got it. I've added this task:");
            System.out.println("  " + t);
            System.out.println("Now you have " + BaronState.getTasks().size() + " tasks in the list.");
        }
    },
    EVENT("event") {
        @Override
        public void execute(String args) throws BaronException {
            String[] parts = args.split(" /from | /to ");
            if (parts.length < 3) {
                throw new BaronException("Invalid format. Please use: event <description> /from <start time> /to <end time>");
            }
            Task t = new Event(parts[0], parts[1], parts[2]);
            BaronState.getTasks().add(t);
            System.out.println("Got it. I've added this task:");
            System.out.println("  " + t);
            System.out.println("Now you have " + BaronState.getTasks().size() + " tasks in the list.");
        }
    },
    DELETE("delete") {
        @Override
        public void execute(String args) throws BaronException {
            try {
                int index = Integer.parseInt(args) - 1;
                Task t = BaronState.delete(index);
                System.out.println("Noted. I've removed this task:");
                System.out.println("  " + t);
                System.out.println("Now you have " + BaronState.getTasks().size() + " tasks in the list.");
            } catch (NumberFormatException e) {
                throw new BaronException("Invalid input. Please provide a valid task number.");
            }
        }
    };

    private final String command;
    Commands(String command) {
        this.command = command;
    }

    // AI suggested use of abstract method to execute commands
    public abstract void execute(String args) throws BaronException;

    public static Commands parse(String input) throws BaronException {
        // AI suggested use of valueOf to parse the input string to enum constant
        try {
            return Commands.valueOf(input.toUpperCase());
        } catch (IllegalArgumentException e) {
            throw new BaronException("Invalid command. Please try again.");
        }
    }
}
